"""Add insemination_time to breeding_logs

Revision ID: 2f1b3d6fcd02
Revises: c8f4a1b2d3e5
Create Date: 2026-08-26 22:42:11.409398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1b3d6fcd02'
down_revision = 'c8f4a1b2d3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('sales_ledger_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_ledger_id'], ['sales_ledger.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_sales_ledger_id'), ['sales_ledger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insemination_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('certificate_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('technician_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('farm_location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_repeat_service', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('certificate_image_url', sa.String(length=255), nullable=True))

    op.alter_column('breeding_logs', 'is_repeat_service', server_default=None)

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('buyer_type', sa.String(length=50), nullable=False, server_default='Individual'))
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agreed_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_buyers_farm_id'), ['farm_id'], unique=False)

    op.alter_column('buyers', 'buyer_type', server_default=None)
    op.alter_column('buyers', 'agreed_rate_per_liter', server_default=None)

    with op.batch_alter_table('feed_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_batches_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('payroll_run_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_run_line_items_run_id'))
        batch_op.create_index(batch_op.f('ix_payroll_run_line_items_payroll_run_id'), ['payroll_run_id'], unique=False)

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=True))

    op.execute("UPDATE sales_ledger SET total_cost = total_amount WHERE total_cost IS NULL")
    op.alter_column('sales_ledger', 'total_cost', nullable=False)
    op.alter_column('sales_ledger', 'amount_paid', server_default=None)

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sales_ledger_tenant_buyer_date', ['tenant_id', 'buyer_id', 'date'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_foreign_key(None, 'buyers', ['buyer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_buyer_id'))
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sales_ledger_tenant_buyer_date', type_='unique')
        batch_op.drop_column('shift')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('total_cost')

    with op.batch_alter_table('payroll_run_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_run_line_items_payroll_run_id'))
        batch_op.create_index(batch_op.f('ix_payroll_run_line_items_run_id'), ['payroll_run_id'], unique=False)

    with op.batch_alter_table('feed_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_batches_recipe_id'))

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyers_farm_id'))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('agreed_rate_per_liter')
        batch_op.drop_column('farm_id')
        batch_op.drop_column('buyer_type')
        batch_op.drop_column('whatsapp')

    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.drop_column('certificate_image_url')
        batch_op.drop_column('is_repeat_service')
        batch_op.drop_column('service_fee')
        batch_op.drop_column('farm_location')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('technician_name')
        batch_op.drop_column('certificate_number')
        batch_op.drop_column('insemination_time')

    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_sales_ledger_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_buyer_id'))

    op.drop_table('buyer_audit_logs')
    # ### end Alembic commands ###
