"""Initial production schema

Revision ID: 4a79e041ba7f
Revises:
Create Date: 2026-09-23 19:22:51.382339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a79e041ba7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genetic_trait_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tenant_type', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('buyer_type', sa.String(length=50), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('agreed_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='_tenant_buyer_name_uc')
    )
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyers_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('breed_status', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('sire_name', sa.String(length=100), nullable=True),
    sa.Column('genetic_score', sa.Integer(), nullable=True),
    sa.Column('birth_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('last_calving_date', sa.Date(), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_hardlocked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dam_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cows_tag_number'), ['tag_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cows_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_cows_tenant_active_tag_number', ['tenant_id', 'tag_number'], unique=True, postgresql_where=sa.text('is_active IS TRUE'))

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('daily_contract_liters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone_number', name='_tenant_phone_uc')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('expense_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_ledger_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feeding_group_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feeding_group', sa.String(length=40), nullable=False),
    sa.Column('avg_body_weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('dmi_percent_bw', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_protein_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feeding_times_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("feeding_group IN ('lactating', 'dry', 'calf_0_3m', 'calf_3_6m', 'heifer')", name='ck_feeding_group_profiles_group_valid'),
    sa.CheckConstraint('avg_body_weight_kg > 0', name='ck_feeding_group_profiles_body_weight_positive'),
    sa.CheckConstraint('dmi_percent_bw > 0 AND dmi_percent_bw <= 10', name='ck_feeding_group_profiles_dmi_range'),
    sa.CheckConstraint('feeding_times_per_day > 0 AND feeding_times_per_day <= 12', name='ck_feeding_group_profiles_times_range'),
    sa.CheckConstraint('target_protein_percent > 0 AND target_protein_percent <= 100', name='ck_feeding_group_profiles_protein_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'feeding_group', name='uq_feeding_group_profiles_tenant_group')
    )
    with op.batch_alter_table('feeding_group_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_group_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('herdsman_routine_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('task_title', sa.String(length=100), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist_items', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('herdsman_routine_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_herdsman_routine_template_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_path', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_mimetype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PROCESSING', 'COMPLETED')", name='ck_idempotency_records_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'actor_id', 'idempotency_key', name='uq_idempotency_records_scope_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_cost_per_kg', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_cost_per_kg >= 0', name='ck_ingredients_current_cost_non_negative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_ingredients_stock_quantity_non_negative'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_ingredients_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_ingredients_tenant_name')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_ingredients_tenant_name', ['tenant_id', 'name'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('energy_mj_per_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('protein_grams_per_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fiber_grams_per_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowed_mixers', sa.String(length=120), nullable=False),
    sa.Column('mixer_role', sa.String(length=50), nullable=False),
    sa.Column('inclusion_percentage_dairy_meal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('inclusion_percentage_main_meal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_inventory_items_tenant_name'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_inventory_items_tenant_sku')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('receipt_number_sequences',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'fiscal_year')
    )
    op.create_table('semen_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bull_name', sa.String(length=100), nullable=False),
    sa.Column('straw_code', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_level', sa.Integer(), nullable=False),
    sa.Column('traits_to_improve', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'straw_code', name='uq_semen_inventory_tenant_straw_code')
    )
    with op.batch_alter_table('semen_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semen_inventory_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('farm_location', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_password_reset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('animal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_events_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_events_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('animal_yield_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('target_liters', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('times_to_feed_daily', sa.Integer(), nullable=False),
    sa.Column('base_herd_feed_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('milking_topup_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('times_to_feed_daily IN (2, 3, 4)', name='ck_animal_yield_targets_times_to_feed_daily_valid'),
    sa.ForeignKeyConstraint(['animal_id'], ['cows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal_yield_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_yield_targets_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_yield_targets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('breeding_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('inventory_semen_id', sa.Integer(), nullable=True),
    sa.Column('external_sire_code', sa.String(length=100), nullable=True),
    sa.Column('provided_by', sa.String(length=20), nullable=False),
    sa.Column('sire_pta_scores', sa.JSON(), nullable=True),
    sa.Column('insemination_date', sa.Date(), nullable=False),
    sa.Column('insemination_time', sa.Time(), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=True),
    sa.Column('technician_name', sa.String(length=120), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('farm_location', sa.String(length=150), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_repeat_service', sa.Boolean(), nullable=False),
    sa.Column('certificate_image_url', sa.String(length=255), nullable=True),
    sa.Column('expected_calving_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("provided_by IN ('FARM', 'VET')", name='ck_breeding_logs_provided_by_valid'),
    sa.CheckConstraint("status IN ('Pending', 'Pregnant', 'Failed', 'Calved')", name='ck_breeding_logs_status_valid'),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['inventory_semen_id'], ['semen_inventory.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_logs_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_logs_inventory_semen_id'), ['inventory_semen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('buyer_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('daily_task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('herdsman_id', sa.Integer(), nullable=False),
    sa.Column('issue_tag', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Completed', 'Deviated')", name='ck_daily_task_logs_status_valid'),
    sa.ForeignKeyConstraint(['herdsman_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routine_id'], ['herdsman_routine_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_task_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_task_logs_herdsman_id'), ['herdsman_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_logs_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('liters_delivered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personal_consumption_liters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billable_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('billable_liters = 0 OR price_per_liter > 0', name='ck_deliveries_billable_price_positive'),
    sa.CheckConstraint('total_price = billable_liters * price_per_liter', name='ck_deliveries_total_matches_snapshot'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('onboarding_status', sa.String(length=30), nullable=False),
    sa.Column('onboarding_invite_nonce', sa.String(length=32), nullable=True),
    sa.Column('onboarding_invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=True),
    sa.Column('leave_start_date', sa.Date(), nullable=True),
    sa.Column('leave_end_date', sa.Date(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('unpaid_leave_days_this_month', sa.Integer(), nullable=False),
    sa.Column('medical_certifications', sa.JSON(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('return_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_verification_decision', sa.String(length=20), nullable=True),
    sa.Column('return_verification_note', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_card_doc_url', sa.String(length=255), nullable=True),
    sa.Column('contract_doc_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("onboarding_status IN ('NONE', 'INVITE_PENDING', 'PASSWORD_RESET_REQUIRED', 'ACTIVE', 'DISABLED')", name='ck_employees_onboarding_status_valid'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id_number', name='uq_employees_tenant_id_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('farm_measurement_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('kg_equivalent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'item_id', 'unit_name', name='uq_tenant_item_unit')
    )
    with op.batch_alter_table('farm_measurement_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_measurement_units_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farm_measurement_units_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feed_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_feed_formulas_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_feed_formulas_tenant_name')
    )
    with op.batch_alter_table('feed_formulas', schema=None) as batch_op:
        batch_op.create_index('ix_feed_formulas_tenant_created_at', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_formulas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feed_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=100), nullable=False),
    sa.Column('target_protein_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recipe_type', sa.String(length=40), nullable=False),
    sa.Column('feeding_group', sa.String(length=40), nullable=True),
    sa.Column('quantity_basis', sa.String(length=30), nullable=False),
    sa.Column('concentrate_kg_per_head_day', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('bulk_density_kg_per_litre', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('bucket_volume_litres', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('scoop_weight_kg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint("feeding_group IS NULL OR feeding_group IN ('lactating', 'dry', 'calf_0_3m', 'calf_3_6m', 'heifer')", name='ck_feed_recipes_feeding_group_valid'),
    sa.CheckConstraint("quantity_basis IN ('total_ration', 'concentrate')", name='ck_feed_recipes_quantity_basis_valid'),
    sa.CheckConstraint("recipe_type IN ('dairy_meal', 'main_meal')", name='ck_feed_recipes_recipe_type_valid'),
    sa.CheckConstraint('bucket_volume_litres IS NULL OR bucket_volume_litres > 0', name='ck_feed_recipes_bucket_volume_positive'),
    sa.CheckConstraint('bulk_density_kg_per_litre IS NULL OR bulk_density_kg_per_litre > 0', name='ck_feed_recipes_bulk_density_positive'),
    sa.CheckConstraint('concentrate_kg_per_head_day IS NULL OR concentrate_kg_per_head_day > 0', name='ck_feed_recipes_concentrate_rate_positive'),
    sa.CheckConstraint('scoop_weight_kg IS NULL OR scoop_weight_kg > 0', name='ck_feed_recipes_scoop_weight_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_feed_recipes_tenant_id')
    )
    with op.batch_alter_table('feed_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_recipes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('genetic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genetic_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genetic_profiles_cow_id'), ['cow_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_genetic_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ingredient_category_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('protein_grams_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('energy_mj_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_grams_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('standards_version', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category', 'standards_version', name='uq_ing_baseline_tenant_category_version')
    )
    with op.batch_alter_table('ingredient_category_baselines', schema=None) as batch_op:
        batch_op.create_index('ix_ing_baseline_tenant_category', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_category_baselines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ingredient_standard_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_standard_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_standard_sync_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ingredient_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('canonical_name', sa.String(length=120), nullable=False),
    sa.Column('protein_grams_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('energy_mj_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_grams_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('standards_version', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_name', 'standards_version', name='uq_ing_std_tenant_name_version')
    )
    with op.batch_alter_table('ingredient_standards', schema=None) as batch_op:
        batch_op.create_index('ix_ing_std_tenant_name', ['tenant_id', 'canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_standards_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('received_quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_rating', sa.String(length=20), nullable=True),
    sa.Column('actual_protein_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.CheckConstraint("quality_rating IN ('Excellent', 'Standard', 'Poor')", name='ck_inventory_batches_quality_rating_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'item_id', 'supplier_name', 'received_date', name='uq_tenant_item_supplier_date')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lactation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('insemination_date', sa.Date(), nullable=True),
    sa.Column('expected_calving_date', sa.Date(), nullable=True),
    sa.Column('drying_date', sa.Date(), nullable=True),
    sa.Column('steaming_date', sa.Date(), nullable=True),
    sa.Column('actual_calving_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('medication', sa.String(length=255), nullable=True),
    sa.Column('withdrawal_days_recommended', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('milk_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('disposition_type', sa.String(length=30), nullable=False),
    sa.Column('disposition_date', sa.Date(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calf_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("disposition_type != 'CALF_FEED' OR calf_id IS NOT NULL", name='ck_milk_dispositions_calf_required'),
    sa.CheckConstraint("disposition_type IN ('CALF_FEED')", name='ck_milk_dispositions_type_valid'),
    sa.CheckConstraint('liters > 0', name='ck_milk_dispositions_liters_positive'),
    sa.ForeignKeyConstraint(['calf_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milk_dispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_dispositions_calf_id'), ['calf_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milk_dispositions_disposition_date'), ['disposition_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milk_dispositions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('milk_drop_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('missing_milk_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('selected_reasons', sa.JSON(), nullable=True),
    sa.Column('investigated_by', sa.Integer(), nullable=True),
    sa.Column('investigated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'INVESTIGATING', 'RESOLVED')", name='ck_milk_drop_alerts_status_valid'),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['investigated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milk_drop_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_drop_alerts_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milk_drop_alerts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_milk_drop_alerts_tenant_status_date', ['tenant_id', 'status', 'alert_date'], unique=False)

    op.create_table('milk_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('amount_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('butterfat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_saleable', sa.Boolean(), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('RECORDED', 'ISOLATED', 'FLAGGED', 'VERIFIED')", name='ck_milk_logs_status_valid'),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milk_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milk_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_gross_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_net_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('Draft', 'Finalized', 'Paid', 'Cancelled')", name='ck_payroll_runs_status_valid'),
    sa.CheckConstraint('payroll_month >= 1 AND payroll_month <= 12', name='ck_payroll_runs_month_valid'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payroll_year', 'payroll_month', name='uq_payroll_runs_period')
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sales_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('liters_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_status IN ('PAID', 'UNPAID', 'PARTIALLY_PAID')", name='ck_sales_ledger_payment_status_valid'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'buyer_id', 'date', name='uq_sales_ledger_tenant_buyer_date')
    )
    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_ledger_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_ledger_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_ledger_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('DEBIT', 'CREDIT', 'PAYMENT', 'EXPENSE', 'REVENUE', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('MILK_SALE', 'LIVESTOCK_SALE', 'OTHER_INCOME', 'PAYMENT', 'INVENTORY_WRITE_OFF', 'OTHER', 'FEED_PURCHASE', 'VET_FEES', 'LABOR_WAGES', 'UTILITIES', 'EQUIPMENT_MAINTENANCE', 'TRANSPORT', 'OPENING_BALANCE', 'BUYER_PAYMENT', name='transactioncategory', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('cost_class', sa.Enum('COGS', 'CUSTOMER_ACQUISITION', 'OPERATING', 'CAPITAL', name='costclass', native_enum=False), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('counterparty_name', sa.String(length=120), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('corrected_from_transaction_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(transaction_type = 'PAYMENT') = (category IN ('PAYMENT', 'BUYER_PAYMENT'))", name='ck_transactions_payment_classification'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['corrected_from_transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'reference_code', name='uq_transactions_tenant_reference_code')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_corrected_from_transaction_id'), ['corrected_from_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('current_flow', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('expected_command_ids', sa.JSON(), nullable=False),
    sa.Column('payload_context', sa.JSON(), nullable=False),
    sa.Column('last_message_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wa_id', name='uq_chat_sessions_tenant_wa_id')
    )
    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_chat_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vet_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('reason_for_visit', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('follow_up_status', sa.String(length=20), nullable=False),
    sa.Column('follow_up_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("follow_up_status IN ('Not Required', 'Pending', 'Scheduled', 'Completed', 'Overdue', 'Cancelled')", name='ck_vet_visits_follow_up_status_valid'),
    sa.ForeignKeyConstraint(['animal_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vet_visits_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vet_visits_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vet_visits_vet_id'), ['vet_id'], unique=False)

    op.create_table('animal_cost_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.Enum('PURCHASE', 'CALF_FEED', 'HEIFER_FEED', 'BREEDING', 'VETERINARY', 'LABOR', 'HOUSING', 'OVERHEAD', 'OTHER', name='animalcosttype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('attribution_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("attribution_method IN ('DIRECT', 'ALLOCATED')", name='ck_animal_cost_allocations_attribution_method_valid'),
    sa.CheckConstraint('amount > 0', name='ck_animal_cost_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('animal_cost_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_cost_allocations_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index('ix_animal_cost_allocations_tenant_cow_date', ['tenant_id', 'cow_id', 'occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_cost_allocations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feed_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mixed_on', sa.Date(), nullable=False),
    sa.Column('depleted_on', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'DEPLETED', 'VOIDED')", name='ck_feed_batches_status_valid'),
    sa.CheckConstraint('cost_per_kg >= 0', name='ck_feed_batches_cost_per_kg_non_negative'),
    sa.CheckConstraint('depleted_on IS NULL OR depleted_on >= mixed_on', name='ck_feed_batches_depleted_after_mixed'),
    sa.CheckConstraint('total_cost >= 0', name='ck_feed_batches_total_cost_non_negative'),
    sa.CheckConstraint('total_weight > 0', name='ck_feed_batches_total_weight_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'formula_id'], ['feed_formulas.tenant_id', 'feed_formulas.id'], name='fk_feed_batches_formula_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'recipe_id'], ['feed_recipes.tenant_id', 'feed_recipes.id'], name='fk_feed_batches_recipe_tenant', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_feed_batches_tenant_id')
    )
    with op.batch_alter_table('feed_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_batches_formula_id'), ['formula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_batches_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_batches_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_feed_batches_tenant_recipe', ['tenant_id', 'recipe_id'], unique=False)
        batch_op.create_index('ix_feed_batches_tenant_status_mixed_on', ['tenant_id', 'status', 'mixed_on'], unique=False)

    op.create_table('formula_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('default_weight', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_weight > 0', name='ck_formula_ingredients_default_weight_positive'),
    sa.ForeignKeyConstraint(['tenant_id', 'formula_id'], ['feed_formulas.tenant_id', 'feed_formulas.id'], name='fk_formula_ingredients_formula_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'ingredient_id'], ['ingredients.tenant_id', 'ingredients.id'], name='fk_formula_ingredients_ingredient_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'formula_id', 'ingredient_id', name='uq_formula_ingredients_formula_ingredient')
    )
    with op.batch_alter_table('formula_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formula_ingredients_formula_id'), ['formula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formula_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index('ix_formula_ingredients_tenant_formula', ['tenant_id', 'formula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formula_ingredients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('genetic_trait_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('trait_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('scored_source', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reliability >= 0 AND reliability <= 100', name='ck_genetic_trait_score_reliability'),
    sa.ForeignKeyConstraint(['profile_id'], ['genetic_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_definition_id'], ['genetic_trait_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'trait_definition_id', name='uq_genetic_trait_score_profile_trait')
    )
    with op.batch_alter_table('genetic_trait_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genetic_trait_scores_profile_id'), ['profile_id'], unique=False)

    op.create_table('heat_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('signs', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_window_start', sa.Date(), nullable=False),
    sa.Column('next_window_end', sa.Date(), nullable=False),
    sa.Column('breeding_log_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("intensity IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_heat_observations_intensity_valid'),
    sa.CheckConstraint('next_window_end >= next_window_start', name='ck_heat_observations_window_valid'),
    sa.ForeignKeyConstraint(['breeding_log_id'], ['breeding_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breeding_log_id')
    )
    with op.batch_alter_table('heat_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heat_observations_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index('ix_heat_observations_tenant_cow_observed', ['tenant_id', 'cow_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_heat_observations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ingredient_standard_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('synonym', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['ingredient_standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_id', 'synonym', name='uq_ing_std_synonym_per_standard')
    )
    with op.batch_alter_table('ingredient_standard_synonyms', schema=None) as batch_op:
        batch_op.create_index('ix_ing_std_synonym_lookup', ['synonym'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_standard_synonyms_standard_id'), ['standard_id'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_transaction_value', sa.Numeric(precision=12, scale=2), sa.Computed('quantity * unit_cost', persisted=True), nullable=False),
    sa.Column('inventory_batch_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("transaction_type IN ('IN', 'OUT')", name='ck_inventory_transactions_type_valid'),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_inventory_batch_id'), ['inventory_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('sales_ledger_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_ledger_id'], ['sales_ledger.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_sales_ledger_id'), ['sales_ledger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonuses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Pending', 'Paid')", name='ck_payroll_status_valid'),
    sa.CheckConstraint('payroll_month >= 1 AND payroll_month <= 12', name='ck_payroll_month_valid'),
    sa.ForeignKeyConstraint(['staff_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'staff_id', 'payroll_year', 'payroll_month', name='uq_payroll_monthly_snapshot')
    )
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payroll_run_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_leave_days', sa.Integer(), nullable=False),
    sa.Column('overdue_penalty_days', sa.Integer(), nullable=False),
    sa.Column('leave_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overdue_penalty_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=True),
    sa.Column('leave_start_date', sa.Date(), nullable=True),
    sa.Column('leave_end_date', sa.Date(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'staff_id', name='uq_payroll_run_staff')
    )
    with op.batch_alter_table('payroll_run_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_run_line_items_payroll_run_id'), ['payroll_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_run_line_items_staff_id'), ['staff_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=True),
    sa.Column('document_content', sa.LargeBinary(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_receipts_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_receipts_tenant_number'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('inclusion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['feed_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'inventory_item_id', name='uq_recipe_ingredient')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('transaction_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_audit_logs_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('batch_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('locked_cost_per_kg', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('locked_protein_grams_per_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('locked_cost_per_kg >= 0', name='ck_batch_ingredients_locked_cost_non_negative'),
    sa.CheckConstraint('percentage > 0 AND percentage <= 100', name='ck_batch_ingredients_percentage_range'),
    sa.CheckConstraint('weight > 0', name='ck_batch_ingredients_weight_positive'),
    sa.ForeignKeyConstraint(['tenant_id', 'batch_id'], ['feed_batches.tenant_id', 'feed_batches.id'], name='fk_batch_ingredients_batch_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'ingredient_id'], ['ingredients.tenant_id', 'ingredients.id'], name='fk_batch_ingredients_ingredient_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'batch_id', 'ingredient_id', name='uq_batch_ingredients_batch_ingredient')
    )
    with op.batch_alter_table('batch_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_ingredients_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_ingredients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feed_batch_consumption_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('feeding_group', sa.String(length=40), nullable=True),
    sa.Column('consumed_weight', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('consumed_on', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("feeding_group IS NULL OR feeding_group IN ('lactating', 'dry', 'calf_0_3m', 'calf_3_6m', 'heifer')", name='ck_feed_batch_consumption_events_feeding_group_valid'),
    sa.CheckConstraint('consumed_weight > 0', name='ck_feed_batch_consumption_events_weight_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'batch_id'], ['feed_batches.tenant_id', 'feed_batches.id'], name='fk_feed_batch_consumption_events_batch_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_batch_consumption_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_batch_consumption_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_feed_batch_consumption_events_tenant_batch_date', ['tenant_id', 'batch_id', 'consumed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_batch_consumption_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('receipt_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_audit_logs_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_audit_logs_receipt_id'))

    op.drop_table('receipt_audit_logs')
    with op.batch_alter_table('feed_batch_consumption_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_batch_consumption_events_tenant_id'))
        batch_op.drop_index('ix_feed_batch_consumption_events_tenant_batch_date')
        batch_op.drop_index(batch_op.f('ix_feed_batch_consumption_events_batch_id'))

    op.drop_table('feed_batch_consumption_events')
    with op.batch_alter_table('batch_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_ingredients_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_batch_ingredients_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_batch_ingredients_batch_id'))

    op.drop_table('batch_ingredients')
    with op.batch_alter_table('transaction_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_audit_logs_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_audit_logs_tenant_id'))

    op.drop_table('transaction_audit_logs')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_inventory_item_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_farm_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('payroll_run_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_run_line_items_staff_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_run_line_items_payroll_run_id'))

    op.drop_table('payroll_run_line_items')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_staff_id'))

    op.drop_table('payroll')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_sales_ledger_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_inventory_batch_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('ingredient_standard_synonyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_standard_synonyms_standard_id'))
        batch_op.drop_index('ix_ing_std_synonym_lookup')

    op.drop_table('ingredient_standard_synonyms')
    with op.batch_alter_table('heat_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heat_observations_tenant_id'))
        batch_op.drop_index('ix_heat_observations_tenant_cow_observed')
        batch_op.drop_index(batch_op.f('ix_heat_observations_cow_id'))

    op.drop_table('heat_observations')
    with op.batch_alter_table('genetic_trait_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genetic_trait_scores_profile_id'))

    op.drop_table('genetic_trait_scores')
    with op.batch_alter_table('formula_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formula_ingredients_tenant_id'))
        batch_op.drop_index('ix_formula_ingredients_tenant_formula')
        batch_op.drop_index(batch_op.f('ix_formula_ingredients_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_formula_ingredients_formula_id'))

    op.drop_table('formula_ingredients')
    with op.batch_alter_table('feed_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_feed_batches_tenant_status_mixed_on')
        batch_op.drop_index('ix_feed_batches_tenant_recipe')
        batch_op.drop_index(batch_op.f('ix_feed_batches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feed_batches_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_feed_batches_formula_id'))

    op.drop_table('feed_batches')
    with op.batch_alter_table('animal_cost_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_cost_allocations_tenant_id'))
        batch_op.drop_index('ix_animal_cost_allocations_tenant_cow_date')
        batch_op.drop_index(batch_op.f('ix_animal_cost_allocations_cow_id'))

    op.drop_table('animal_cost_allocations')
    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vet_visits_vet_id'))
        batch_op.drop_index(batch_op.f('ix_vet_visits_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vet_visits_animal_id'))

    op.drop_table('vet_visits')
    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_chat_sessions_tenant_id'))

    op.drop_table('user_chat_sessions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_code'))
        batch_op.drop_index(batch_op.f('ix_transactions_farm_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_corrected_from_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_buyer_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_ledger_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sales_ledger_date'))
        batch_op.drop_index(batch_op.f('ix_sales_ledger_buyer_id'))

    op.drop_table('sales_ledger')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_runs_farm_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('milk_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milk_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_milk_logs_tenant_id'))

    op.drop_table('milk_logs')
    with op.batch_alter_table('milk_drop_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_milk_drop_alerts_tenant_status_date')
        batch_op.drop_index(batch_op.f('ix_milk_drop_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_milk_drop_alerts_cow_id'))

    op.drop_table('milk_drop_alerts')
    with op.batch_alter_table('milk_dispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milk_dispositions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_milk_dispositions_disposition_date'))
        batch_op.drop_index(batch_op.f('ix_milk_dispositions_calf_id'))

    op.drop_table('milk_dispositions')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_tenant_id'))

    op.drop_table('medical_records')
    op.drop_table('lactation_cycles')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_item_id'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('ingredient_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_standards_tenant_id'))
        batch_op.drop_index('ix_ing_std_tenant_name')

    op.drop_table('ingredient_standards')
    with op.batch_alter_table('ingredient_standard_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_standard_sync_jobs_tenant_id'))

    op.drop_table('ingredient_standard_sync_jobs')
    with op.batch_alter_table('ingredient_category_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_category_baselines_tenant_id'))
        batch_op.drop_index('ix_ing_baseline_tenant_category')

    op.drop_table('ingredient_category_baselines')
    with op.batch_alter_table('genetic_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genetic_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_genetic_profiles_cow_id'))

    op.drop_table('genetic_profiles')
    with op.batch_alter_table('feed_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_recipes_tenant_id'))

    op.drop_table('feed_recipes')
    with op.batch_alter_table('feed_formulas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_formulas_tenant_id'))
        batch_op.drop_index('ix_feed_formulas_tenant_created_at')

    op.drop_table('feed_formulas')
    with op.batch_alter_table('farm_measurement_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_measurement_units_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_farm_measurement_units_item_id'))

    op.drop_table('farm_measurement_units')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_tenant_id'))

    op.drop_table('employees')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_date'))
        batch_op.drop_index(batch_op.f('ix_deliveries_customer_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('daily_task_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_task_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_daily_task_logs_routine_id'))
        batch_op.drop_index(batch_op.f('ix_daily_task_logs_herdsman_id'))

    op.drop_table('daily_task_logs')
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_buyer_id'))

    op.drop_table('buyer_audit_logs')
    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_logs_inventory_semen_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_logs_cow_id'))

    op.drop_table('breeding_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('animal_yield_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_yield_targets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_animal_yield_targets_animal_id'))

    op.drop_table('animal_yield_targets')
    with op.batch_alter_table('animal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_animal_events_created_by'))
        batch_op.drop_index(batch_op.f('ix_animal_events_cow_id'))

    op.drop_table('animal_events')
    op.drop_table('users')
    with op.batch_alter_table('semen_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semen_inventory_tenant_id'))

    op.drop_table('semen_inventory')
    op.drop_table('receipt_number_sequences')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_name'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_tenant_name')
        batch_op.drop_index(batch_op.f('ix_ingredients_tenant_id'))

    op.drop_table('ingredients')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_tenant_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('herdsman_routine_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_herdsman_routine_template_tenant_id'))

    op.drop_table('herdsman_routine_template')
    with op.batch_alter_table('feeding_group_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_group_profiles_tenant_id'))

    op.drop_table('feeding_group_profiles')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_tenant_id'))

    op.drop_table('farms')
    with op.batch_alter_table('expense_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_ledger_tenant_id'))

    op.drop_table('expense_ledger')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tenant_id'))

    op.drop_table('customers')
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_index('uq_cows_tenant_active_tag_number', postgresql_where=sa.text('is_active IS TRUE'))
        batch_op.drop_index(batch_op.f('ix_cows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cows_tag_number'))

    op.drop_table('cows')
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buyers_farm_id'))

    op.drop_table('buyers')
    op.drop_table('tenants')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    op.drop_table('genetic_trait_definitions')
    # ### end Alembic commands ###
