"""add deliveries table and customer agreed_rate_per_liter

Revision ID: 513aa6d621d6
Revises: c2183734828b
Create Date: 2026-08-10 16:34:07.864315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513aa6d621d6'
down_revision = 'c2183734828b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('liters_delivered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personal_consumption_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billable_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_billed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreed_rate_per_liter', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('agreed_rate_per_liter')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_date'))
        batch_op.drop_index(batch_op.f('ix_deliveries_customer_id'))

    op.drop_table('deliveries')
    # ### end Alembic commands ###
