"""Add Buyer and SalesLedger models

Revision ID: 711cd123980a
Revises: a3f10cb7f5db
Create Date: 2026-08-17 12:43:44.649518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '711cd123980a'
down_revision = 'a3f10cb7f5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_sales_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_transaction_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_buyer_audit_tenant_buyer'))
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_tenant_id'))

    op.drop_table('buyer_audit_logs')
    # Backfill NULL phone numbers before making the column non-nullable.
    op.execute("UPDATE buyers SET phone_number = 'UNKNOWN' WHERE phone_number IS NULL OR phone_number = ''")

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_buyers_farm_id'))
        batch_op.drop_index(batch_op.f('ix_buyers_name'))
        batch_op.drop_constraint(batch_op.f('uq_buyers_tenant_name'), type_='unique')
        batch_op.create_unique_constraint('_tenant_buyer_name_uc', ['tenant_id', 'name'])
        batch_op.drop_constraint(batch_op.f('buyers_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('agreed_rate_per_liter')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('farm_id')
        batch_op.drop_column('buyer_type')
        batch_op.drop_column('whatsapp')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Active'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_customers_phone_number'))
        batch_op.drop_constraint(batch_op.f('uq_customers_tenant_phone_number'), type_='unique')
        batch_op.create_unique_constraint('_tenant_phone_uc', ['tenant_id', 'phone_number'])
        batch_op.drop_constraint(batch_op.f('customers_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('is_active')

    # Remove the server-side default for 'status' after backfilling.
    op.alter_column('customers', 'status', server_default=None)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.alter_column('personal_consumption_liters',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('deliveries_tenant_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deliveries_recorded_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deliveries_customer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('deliveries_transaction_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('recorded_by')
        batch_op.drop_column('rate_per_liter')
        batch_op.drop_column('amount_billed')
        batch_op.drop_column('transaction_id')

    op.alter_column('deliveries', 'price_per_liter', server_default=None)
    op.alter_column('deliveries', 'total_price', server_default=None)

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_sales_ledger_tenant_buyer_date'), type_='unique')
        batch_op.drop_constraint(batch_op.f('sales_ledger_buyer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sales_ledger_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'buyers', ['buyer_id'], ['id'])
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('shift')

    op.alter_column('sales_ledger', 'price_per_liter', server_default=None)
    op.alter_column('sales_ledger', 'total_amount', server_default=None)

    # Pre-migration data cleanup: Standardize 'Milk Sale' to 'MILK_SALE' for the enum.
    op.execute("UPDATE transactions SET category = 'MILK_SALE' WHERE category = 'Milk Sale'")

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEBIT', 'CREDIT', 'EXPENSE', name='transactiontype', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MILK_SALE', 'PAYMENT', 'INVENTORY_WRITE_OFF', 'OTHER', name='transactioncategory', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('recorded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reference_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_transactions_reference_code'))
        batch_op.create_index(batch_op.f('ix_transactions_reference_code'), ['reference_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('transactions_buyer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('transactions_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('buyer_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'CLEARED'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transactions_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('transactions_buyer_id_fkey'), 'buyers', ['buyer_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_code'))
        batch_op.create_index(batch_op.f('ix_transactions_reference_code'), ['reference_code'], unique=True)
        batch_op.alter_column('reference_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('recorded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.Enum('MILK_SALE', 'PAYMENT', 'INVENTORY_WRITE_OFF', 'OTHER', name='transactioncategory', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('DEBIT', 'CREDIT', 'EXPENSE', name='transactiontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # Revert 'MILK_SALE' back to 'Milk Sale' on downgrade.
    op.execute("UPDATE transactions SET category = 'Milk Sale' WHERE category = 'MILK_SALE'")

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.VARCHAR(length=20), server_default=sa.text("'Morning'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sales_ledger_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('sales_ledger_buyer_id_fkey'), 'buyers', ['buyer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_unique_constraint(batch_op.f('uq_sales_ledger_tenant_buyer_date'), ['tenant_id', 'buyer_id', 'date'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('price_per_liter')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount_billed', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate_per_liter', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('deliveries_transaction_id_fkey'), 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('deliveries_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('deliveries_recorded_by_fkey'), 'users', ['recorded_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('deliveries_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('personal_consumption_liters',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('total_price')
        batch_op.drop_column('price_per_liter')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customers_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('_tenant_phone_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_customers_tenant_phone_number'), ['tenant_id', 'phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_number'), ['phone_number'], unique=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('buyer_type', sa.VARCHAR(length=50), server_default=sa.text("'Individual'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('agreed_rate_per_liter', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('buyers_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('_tenant_buyer_name_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_buyers_tenant_name'), ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_buyers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyers_farm_id'), ['farm_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('contact_person')

    op.create_table('buyer_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('previous_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], name=op.f('buyer_audit_logs_buyer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('buyer_audit_logs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('buyer_audit_logs_pkey'))
    )
    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_buyer_audit_tenant_buyer'), ['tenant_id', 'buyer_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_ledger_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_applied', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sales_ledger_id'], ['sales_ledger.id'], name=op.f('fk_payment_allocations_sales_ledger_id_sales_ledger'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payment_allocations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_payment_allocations_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_sales_ledger_id'), ['sales_ledger_id'], unique=False)

    # ### end Alembic commands ###
