"""Added Store, Requisition, and MilkLog models

Revision ID: 7ee1ca7ae589
Revises: 541c7f01a8f2
Create Date: 2026-04-15 21:38:15.371840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee1ca7ae589'
down_revision = '541c7f01a8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_items_name'), ['name'], unique=True)

    op.create_table('feed_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('target_cow_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['store_items.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_requisitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_requisitions_timestamp'), ['timestamp'], unique=False)

    op.create_table('milk_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('amount_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('is_saleable', sa.Boolean(), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milk_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milk_logs_timestamp'))

    op.drop_table('milk_logs')
    with op.batch_alter_table('feed_requisitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_requisitions_timestamp'))

    op.drop_table('feed_requisitions')
    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_items_name'))

    op.drop_table('store_items')
    # ### end Alembic commands ###
