"""Add status column to transactions

Revision ID: 83569697568d
Revises: 513aa6d621d6
Create Date: 2026-08-11 02:05:16.484171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83569697568d'
down_revision = '513aa6d621d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='CLEARED', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
