"""add user_chat_sessions and user phone_number

Revision ID: 8e6540799a52
Revises: a4b5c6d7e8f9
Create Date: 2026-08-20 16:21:57.075719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6540799a52'
down_revision = 'a4b5c6d7e8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('last_message_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone_number', name='uq_chat_sessions_tenant_phone')
    )
    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_chat_sessions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_chat_sessions_tenant_id'))

    op.drop_table('user_chat_sessions')
    # ### end Alembic commands ###
