"""Initial setup

Revision ID: 943215af98d1
Revises: f0a2c4e6b8d1
Create Date: 2026-09-22 18:04:09.002209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '943215af98d1'
down_revision = 'f0a2c4e6b8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_cost_allocations', schema=None) as batch_op:
        batch_op.alter_column('cost_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PURCHASE', 'CALF_FEED', 'HEIFER_FEED', 'BREEDING', 'VETERINARY', 'LABOR', 'HOUSING', 'OVERHEAD', 'OTHER', name='animalcosttype', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('revoked_tokens_jti_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('MILK_SALE', 'LIVESTOCK_SALE', 'OTHER_INCOME', 'PAYMENT', 'INVENTORY_WRITE_OFF', 'OTHER', 'FEED_PURCHASE', 'VET_FEES', 'LABOR_WAGES', 'UTILITIES', 'EQUIPMENT_MAINTENANCE', 'TRANSPORT', 'OPENING_BALANCE', 'BUYER_PAYMENT', name='transactioncategory', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('cost_class',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('COGS', 'CUSTOMER_ACQUISITION', 'OPERATING', 'CAPITAL', name='costclass', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('cost_class',
               existing_type=sa.Enum('COGS', 'CUSTOMER_ACQUISITION', 'OPERATING', 'CAPITAL', name='costclass', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Enum('MILK_SALE', 'LIVESTOCK_SALE', 'OTHER_INCOME', 'PAYMENT', 'INVENTORY_WRITE_OFF', 'OTHER', 'FEED_PURCHASE', 'VET_FEES', 'LABOR_WAGES', 'UTILITIES', 'EQUIPMENT_MAINTENANCE', 'TRANSPORT', 'OPENING_BALANCE', 'BUYER_PAYMENT', name='transactioncategory', native_enum=False),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('revoked_tokens_jti_key'), ['jti'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('animal_cost_allocations', schema=None) as batch_op:
        batch_op.alter_column('cost_type',
               existing_type=sa.Enum('PURCHASE', 'CALF_FEED', 'HEIFER_FEED', 'BREEDING', 'VETERINARY', 'LABOR', 'HOUSING', 'OVERHEAD', 'OTHER', name='animalcosttype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
