"""Added Livestock, Lactation, and Medical models

Revision ID: 9480f42224ab
Revises: bf2e7bc01ecd
Create Date: 2026-04-15 20:26:28.604510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9480f42224ab'
down_revision = 'bf2e7bc01ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('breed_status', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('sire_name', sa.String(length=100), nullable=True),
    sa.Column('is_hardlocked', sa.Boolean(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cows_tag_number'), ['tag_number'], unique=True)

    op.create_table('lactation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('insemination_date', sa.Date(), nullable=True),
    sa.Column('expected_calving_date', sa.Date(), nullable=True),
    sa.Column('drying_date', sa.Date(), nullable=True),
    sa.Column('steaming_date', sa.Date(), nullable=True),
    sa.Column('actual_calving_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('medication', sa.String(length=255), nullable=True),
    sa.Column('withdrawal_days_recommended', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.drop_table('lactation_cycles')
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cows_tag_number'))

    op.drop_table('cows')
    # ### end Alembic commands ###
