"""Add payment allocations and inventory reason codes

Revision ID: a1b2c3d4e5f8
Revises: bc34de56fa78
Create Date: 2026-07-08 11:20:11.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f8'
down_revision = 'bc34de56fa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('sales_ledger_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_ledger_id'], ['sales_ledger.id'], name=op.f('fk_payment_allocations_sales_ledger_id_sales_ledger'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payment_allocations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_payment_allocations_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_sales_ledger_id'), ['sales_ledger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_code', sa.String(length=50), server_default='STANDARD', nullable=False))
        # Assuming the old column was named 'reference_note' and needs to be renamed to 'notes'
        # If you created 'notes' from scratch and dropped 'reference_note', this would be an add_column.
        # Renaming is better to preserve data.
        # If 'reference_note' does not exist, this line should be removed.
        # batch_op.alter_column('reference_note', new_column_name='notes', existing_type=sa.Text())
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
        batch_op.drop_constraint('ck_sales_ledger_payment_status_valid', type_='check')
        batch_op.create_check_constraint('ck_sales_ledger_payment_status_valid', "payment_status IN ('PAID', 'UNPAID', 'PARTIALLY_PAID')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_constraint('ck_sales_ledger_payment_status_valid', type_='check')
        batch_op.create_check_constraint('ck_sales_ledger_payment_status_valid', "payment_status IN ('PAID', 'UNPAID')")

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('reason_code')

    op.drop_table('payment_allocations')
    # ### end Alembic commands ###