"""Add last_calving_date, pregnancy_status, and due_date to Cow model

Revision ID: a3f10cb7f5db
Revises: 83569697568d
Create Date: 2026-08-14 12:01:25.766531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'a3f10cb7f5db'
down_revision = '83569697568d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add other new columns first
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_calving_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pregnancy_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

        # STEP 1: Add the 'status' column, but temporarily allow NULLs
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

        # Drop the old column that is being replaced
        batch_op.drop_column('current_status')

    # STEP 2: Backfill the database with the exact correct data
    # Mapping the specific statuses you provided to the existing cows
    op.execute(text("UPDATE cows SET status = 'Lactating' WHERE name IN ('Sofia', 'Joyce')"))
    op.execute(text("UPDATE cows SET status = 'In-calf' WHERE name = 'Princess'"))
    op.execute(text("UPDATE cows SET status = 'Calf' WHERE name IN ('Ndegwa', 'Ruby')"))
    # Here is Pesa replacing Mrofu!
    op.execute(text("UPDATE cows SET status = 'Heifer' WHERE name IN ('Mrembo', 'Pesa')"))

    # Catch-all just in case there are other cows without a status set
    op.execute(text("UPDATE cows SET status = 'Lactating' WHERE status IS NULL"))

    # STEP 3: Enforce enterprise data integrity by locking the column to NOT NULL
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'current_status' back, allowing nulls temporarily
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.VARCHAR(length=50), nullable=True))

    # Backfill 'current_status' with data from 'status' before dropping it
    op.execute(text("UPDATE cows SET current_status = status"))

    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.alter_column('current_status', existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('pregnancy_status')
        batch_op.drop_column('last_calving_date')

    # ### end Alembic commands ###
