"""Use partial unique index for active cow tags

Revision ID: c2183734828b
Revises: d6618a9f3faa
Create Date: 2026-07-23 16:20:59.642540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2183734828b'
down_revision = 'd6618a9f3faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_yield_targets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_logs_semen_id'))
        batch_op.create_index(batch_op.f('ix_breeding_logs_inventory_semen_id'), ['inventory_semen_id'], unique=False)

    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buyer_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cows_tenant_tag_number'), type_='unique')
        batch_op.create_index('uq_cows_tenant_active_tag_number', ['tenant_id', 'tag_number'], unique=True, postgresql_where=sa.text('is_active IS TRUE'))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_customers_tenant_phone_number'))
        batch_op.create_unique_constraint('uq_customers_tenant_phone_number', ['tenant_id', 'phone_number'])
        batch_op.create_index(batch_op.f('ix_customers_phone_number'), ['phone_number'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('genetic_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_genetic_profiles_cow_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_genetic_profiles_cow_id'))
        batch_op.create_index(batch_op.f('ix_genetic_profiles_cow_id'), ['cow_id'], unique=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('allowed_mixers',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('mixer_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_column('reference_note')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_buyer_id_buyers_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'buyers', ['buyer_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_buyer_id_buyers_id'), 'buyers', ['buyer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales_ledger', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_note', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('mixer_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('allowed_mixers',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('genetic_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genetic_profiles_cow_id'))
        batch_op.create_index(batch_op.f('ix_genetic_profiles_cow_id'), ['cow_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_genetic_profiles_cow_id'), ['cow_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_phone_number'))
        batch_op.drop_constraint('uq_customers_tenant_phone_number', type_='unique')
        batch_op.create_index(batch_op.f('uq_customers_tenant_phone_number'), ['tenant_id', 'phone_number'], unique=True)

    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_cows_tenant_active_tag_number', postgresql_where=sa.text('is_active IS TRUE'))
        batch_op.create_unique_constraint(batch_op.f('uq_cows_tenant_tag_number'), ['tenant_id', 'tag_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('buyer_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buyer_audit_logs_buyer_id'))

    with op.batch_alter_table('breeding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_logs_inventory_semen_id'))
        batch_op.create_index(batch_op.f('ix_breeding_logs_semen_id'), ['inventory_semen_id'], unique=False)

    with op.batch_alter_table('animal_yield_targets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
