"""Merge enum and model migration heads

Revision ID: d4e5f6a7b8c9
Revises: 1a2b3c4d5e6f, 711cd123980a
Create Date: 2026-08-17 15:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = ('1a2b3c4d5e6f', '711cd123980a')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###