"""rework whatsapp chat session schema for interactive flows

Revision ID: fb98d97abdfd
Revises: 8e6540799a52
Create Date: 2026-08-20 16:46:08.287089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb98d97abdfd'
down_revision = '8e6540799a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wa_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('current_flow', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('expected_command_ids', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('payload_context', sa.JSON(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_chat_sessions_tenant_phone'), type_='unique')
        batch_op.create_unique_constraint('uq_chat_sessions_tenant_wa_id', ['tenant_id', 'wa_id'])
        batch_op.create_foreign_key('fk_chat_sessions_farm', 'farms', ['farm_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('current_state')
        batch_op.drop_column('context_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_chat_sessions_farm', type_='foreignkey')
        batch_op.drop_constraint('uq_chat_sessions_tenant_wa_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_chat_sessions_tenant_phone'), ['tenant_id', 'phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('payload_context')
        batch_op.drop_column('expected_command_ids')
        batch_op.drop_column('current_step')
        batch_op.drop_column('current_flow')
        batch_op.drop_column('wa_id')
        batch_op.drop_column('farm_id')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
